version: '3.8'

services:
  pg:
    image: postgres:14.18-alpine3.22
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
        - "${PG_PORT}:5432"
    volumes:
        - pg_data:/var/lib/postgresql/data