volumes:
  postgres_volume:
  redis-data:

services:
  pg:
    image: postgres:14.18-alpine
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
        - "${PG_PORT}:5432"
    volumes:
        - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:7.2.5-alpine3.20
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data